# Generated by Django 3.1.7 on 2021-04-18 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_category_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
    ]
