# Generated by Django 3.1.7 on 2021-04-26 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ratings',
            field=models.FloatField(default=0),
        ),
    ]
