# Generated by Django 3.1.7 on 2021-04-20 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_wishlisted'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WishListed',
        ),
    ]
