# Generated by Django 3.1.7 on 2021-04-24 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_profile',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/profile_pictures'),
        ),
    ]
